Repository kalgory-com/kalgory-py, pull requests merged in 2024-07, with the labels that each got.

#5 Bridging between WebAssembly component and library consumer
  .github/workflows/ci.yaml
  .gitignore
  README.md
  kalgory/bindings/__init__.py
  kalgory/bindings/block/__init__.py
  kalgory/bindings/block/types.py
  kalgory/component/__init__.py
  kalgory/component/block.py
  library.py
  requirements.txt
  ruff.toml
  setup.py
  tests/.gitignore
  tests/guest.py
  tests/test_kalgory.py
  wit/block.wit
Labels: type: deploy, type: enhancement, type: testing

#9 Parse
  README.md
  kalgory/bindings/block/__init__.py
  kalgory/bindings/block/types.py
  kalgory/component/block.py
  kalgory/component/utility.py
  tests/.gitignore
  tests/guest.py
  tests/test_kalgory.py
Labels: type: feature

#10 Publish to pypi
  README.md
  kalgory/bindings/block/__init__.py
  kalgory/bindings/block/types.py
  kalgory/component/block.py
  kalgory/component/utility.py
  pyproject.toml
  tests/test_kalgory.py
  wit/block.wit
Labels: type: deploy
